### PR TITLE
Rename for upcoming fava 1.20

### PR DESCRIPTION
**Pull request by seltzered**
Fix https://github.com/redstreet/fava_investor/issues/59

### CODE REVIEW

**Comment by redstreet** [comment]
Thanks. Would it be possible to make this backward compatible?

**Comment by aclindsa** [comment]
> Thanks. Would it be possible to make this backward compatible?

In case it helps, I introduced some version detection logic for a similar issue in https://github.com/redstreet/fava_investor/commit/047acbbad8e6f85133eb7eaa5a2ccf6259701b43. Maybe that could be made more generic and re-used here?

**Comment by aclindsa** [comment]
After trying this patch out, I do not believe it is the correct fix. If you look closely at the diff from [beancount/fava@9e99001#diff-34e70ccbc25aaa9a79d126c4b4b93bc93948cb6dfe9bd5b5978d8a1ea4227205](https://github.com/beancount/fava/commit/9e990016ca444d1369bfcd7ff521035a94845c8e#diff-34e70ccbc25aaa9a79d126c4b4b93bc93948cb6dfe9bd5b5978d8a1ea4227205), you will find that the way github is presenting it is misleading. At first glance it may look like `url_for_source` is the new name for `url_for_current`, but in fact `url_for_source` has existed for some time, and `url_for_current` has recently been removed.

When I try out this change I am redirected to `https://example.com/my-finances/editor/?module=aa_class` instead of the expected `https://example.com/my-finances/extension/Investor/?module=aa_class` when clicking on the "Asset Allocation Classes" link on the main fava investor page. This results in me being dumped into the fava editor for my beancount file instead of the expected  asset allocation chart/table.

And this behavior makes sense when you read the comment for the `url_for_source` function: "URL to source file (possibly link to external editor)."

**Comment by aclindsa** [comment]
Maybe @yagebu can help us understand the best way for plugins to reference their own URL here, given the removal of `url_for_current`.

**Comment by yagebu** [comment]
Something like `url_for("extension_report", report_name="ExtensionName", module="....")` should work (and also work with older Fava versions)

**Comment by aclindsa** [comment]
I just made a MR based on the suggestion from @yagebu as https://github.com/redstreet/fava_investor/pull/62. I have tested that it works with the latest fava.

**Pull request closed without merging**
