### PR TITLE
WIP balance split for testing

### PR DESCRIPTION
**Pull request by baartosz**
Hi. Sorry for the size of PR. When I tried with smaller bits earlier it was taking lots of time and effort to progress due to different time zones and all the delays so now I am trying with bigger feature.

Features:
- splitting balance into contributions, withdrawals, dividends, costs, gains realized and unrealized
- pages with separate journals for each of these for easy browse
- "test split" page summarizing all splits and calculating error. An "error" is a difference between sum of splits and value of investment accounts. Its calculated after each transaction and balance is generated as in usual journal view.
- config now has "accounts_income_pattern" and "accounts_expenses_pattern" instead of "accounts_internal_pattern". That allows to differenciate between loses and costs. Make sure to update configuration. Sample is in `example.bc` and in the test suite.
- in the beginning it was using "internalize()" from Martin's returns script. Turned out it wasn't needed so I removed that dependency completely.

For my personal ledger that starts in 2014 it ends up with 0.07 GBP error which seems to be coming from rounding errors in transactions on mutual funds that often are in units with 3-4 decimal places. It doesn't seem crucial to fix these. Please test with your ledger and let me know if it miscalculates splits in any transactions. I didn't go through all my transactions verifying each split yet.

Not implemented yet:
- support fava's account filtering
- graphs
- relative imports

Gains realized and unrealized are currently sums of gains and loses, we could split them further. That would make it easier to visualize i think, pretty much like income and expense charts. Fava doesn't have any stacked bar charts unfortunately...

### CODE REVIEW

**Comment by redstreet** [comment]
This looks like an interesting PR from the description :). However, I was unable to get it to work. It chokes on my sources, and spends over 3 minutes without output. I tried it on `huge-example.beancount` that I checked in recently. It returned some results that didn't make sense to me there. Perhaps my config is off. Would you mind rebasing off my latest commit and modifying `huge-example.beancount` to add in your correct config so it yields the correct results? Thanks!

**Comment by baartosz** [comment]
How many transactions do you have in your ledger? With roughly 1000 entries in mine was a bit slow but few seconds was enough.

**Comment by baartosz** [comment]
I merged master now and put configuration in place. Screenshots shows splits in `huge-example.beancount`.
image
Is this far off of what you would expect? I haven't checked particular transactions yet. I will have more time for it in the evening or tomorrow.

**Comment by baartosz** [comment]
Okay I started going through journals and its clear that contributions and withdrawals are not correct for transactions with more splits.

**Comment by baartosz** [comment]
image
I don't really understand what's going on here with IRAUSD postings. How should they be classified? Withdrawal or a cost maybe?

**Comment by baartosz** [comment]
image
Current state:
- contributions look fine to me
- withdrawals not sure about the 401k transfers to expenses
- dividends transactions are quite obvious here, matches balance of Income:Dividends
- costs - matches Expenses:Finance:Commission
- gains realized - matches etrade gains
- unrealized gains - matches Equity:Unrealized

**Comment by redstreet** [comment]
I'm a bit confused. In contributions, I'm seeing:
```

**Comment by baartosz** [comment]
Split journals are printing all the entries currently. Change column is empty, means its not considered contribution. You're right, i should filter out entries that are not changing the balance. Will do!

**Comment by baartosz** [comment]
Its slow but works fine now.

**Comment by redstreet** [comment]
Nice. Works well for `huge-example.beancount`. My own source, which has about 30k transactions, 40k+ entries, and far more postings, is a challenge to get working. It works sometimes, but seems to timeout or OOM or something at other times. So I'm unable to see if it works as expected for an extensive example. So I'm thinking the next step is to fix performance. What do you think?

BTW, your first post in this PR is very helpful, but I'm a bit lost in connecting it to the code. What does the code do? Could a carefully constructed bean-query insufficient replace the code? If not, why?

**Comment by redstreet** [comment]
A query to find dividends takes only 2 seconds or so on my large source.

This got me thinking: the journal is great as a verification tool, but it may not be worth it if it comes at the cost of code complexity and performance.

It may be simpler, faster to classify postings instead. I'm happy to send you a prototype when I have some time, if you'd like. Let me know.

**Comment by baartosz** [comment]
Code can be cleaner as well certainly. Currently major slowdown i believe is from calculating unrealized gains and error for each transaction. I can make it optional, a "debug mode" and then we'll see if its still slow. In the end it should be aggregating it all only per day/week/month/quarter and separate ledgers should run only of the calculations.

We briefly chatted about using queries before in https://github.com/redstreet/fava_investor/issues/26#issuecomment-609406910

I thought it would be lovely to chart these parts together over time to visualize what contributes to current value of the portfolio hence the single run over the entries to calculate it all. That would require several queries with some aggregations, do you think its doable with queries?

Sure i can look into queries a bit more and see if its going to be better. I would appreciate it if you share your prototype queries :)

**Comment by baartosz** [comment]
> It may be simpler, faster to classify postings instead.

Can you explain what you mean?

**Comment by redstreet** [comment]
> Currently major slowdown i believe is from calculating unrealized gains and error for each transaction. I can make it optional, a "debug mode" and then we'll see if its still slow. In the end it should be aggregating it all only per day/week/month/quarter and separate ledgers should run only of the calculations.

Makes sense. This is a good idea. The goal would be to get to where we can run a 40k journal in preferably 5-8 seconds. Else, I'm concerned development becomes a problem since I'm unable to run a few test cases. It's fine if we don't aggregate anything but the final numbers unless the journal is opened up. We can cross check final numbers using institutional data where available.

With my comment about queries, I was mainly suggesting that a query like this to find dividends for a given account:
```SELECT SUM(position) WHERE account ~ 'Income.*Dividends.*FTrade' AND 'Assets:Investments:FTrade' IN other_accounts```
runs in under 2 seconds on my journal. So at least getting final numbers for what you're doing shouldn't take over 6 seconds or so.

> I thought it would be lovely to chart these parts together over time to visualize what contributes to current value of the portfolio hence the single run over the entries to calculate it all.

What you're saying makes sense. With my earlier comment about designing this with queries, I mentioned it simply to estimate what our code complexity and our runtime should be. If we can run 4 queries like the above to get all we want, then we are doing it with some 10 lines of code, and 5 seconds.

I think I'd focus first on getting the performance down to 5 sec, and then on simplify the code. What do you think?

**Comment by baartosz** [comment]
Sounds good!

**Comment by redstreet** [comment]
I'm trying to figure out how to simplify your code. This was the pseudocode in my mind. I think this is what your code does overall as well, except it reconstructs the journal. Might be simpler to only collect and display postings instead.

```
def add_to_bucket(total, pattern, posting):
  if posting in pattern:
     total += convert(posting.inventory, base_currency)

def classify_postings(entries, start_date, end_date):
  # start_date, end_date filtering not yet implemented
  for entry in entries:
    if there is at least one posting with the value account:
      for posting in postings:
         add_to_bucket(dividends_bucket, dividends_pattern, posting)
         add_to_bucket(capgains_bucket, capgains_pattern, posting)
         add_to_bucket(expenses_bucket, expenses_pattern, posting)
         add_to_bucket(external_bucket, external_pattern, posting)
         if posting in base_pattern:
            base_bucket += posting.inventory
         # if posting not in any known pattern: raise Exception

basis = base_bucket.reduce(cost)
market_value = base_bucket.reduce(market_value)
```

**Comment by baartosz** [comment]
I am in the middle of refactoring already and the idea is to have
"accumulator" class for each type. Each will have process(transaction)
where it will collect relevant postings and add it to previous balance.
When end of interval comes "return_and_reset()" will be called and do
exactly what is says. Each accumulator will be completely separate and only
relevant ones will be selected for each report.
```
For entry in entries:
   For accumulator in accumulators:
       accumulator.process(entry)
   If is_new_interval:
       For accumulator in accumulators:
          accumulator.return and reset()
          # and add it to result

```

**Comment by baartosz** [comment]
Main function `calculate_split_parts()` works with accumulators now. Some journals are faster than others. It will handle your ledger now!

**Comment by redstreet** [comment]
Hmm, I get:
```
Traceback (most recent call last):                                                                                                         [0/261]
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/fava/application.py", line 342, in extension_report
    content = render_template_string(template, extension=extension)
  File "/usr/lib/python3.6/site-packages/flask/templating.py", line 150, in render_template_string
    context, ctx.app)
  File "/usr/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 219, in top-level template code
  File "/usr/lib/python3.6/site-packages/fava/template_filters.py", line 81, in cost_or_value
    convert.convert_position, g.conversion, g.ledger.price_map, date
  File "/usr/lib/python3.6/site-packages/beancount/core/inventory.py", line 305, in reduce
    inventory.add_amount(reducer(position, *args))
  File "/usr/lib/python3.6/site-packages/beancount/core/convert.py", line 169, in convert_position
    date=date, via=(value_currency,))
  File "/usr/lib/python3.6/site-packages/beancount/core/convert.py", line 193, in convert_amount
    _, rate = prices.get_price(price_map, base_quote, date)
  File "/usr/lib/python3.6/site-packages/beancount/core/prices.py", line 261, in get_price
    index = bisect_key.bisect_right_with_key(price_list, date, key=lambda x: x[0])
  File "/usr/lib/python3.6/site-packages/beancount/utils/bisect_key.py", line 54, in bisect_right_with_key
    if x < key(a[mid]):
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'date'
```

A super simple, small PR to start off with that we can build upon might make it easier for me to jump in and debug too :).

**Comment by redstreet** [comment]
I've checked in a very simple splitter into the `split` branch. It's command-line only (no fava). It produces correct results on a few test cases including my own sources and `huge-example.beancount`. Try it out and let me know if that'll work as a base for further work.

**Comment by redstreet** [comment]
Hi @baartosz, are you still interested in writing this module? Thought I'd ask so I can leave it to you vs. picking it up myself or seeing if anyone else is interested. No rush at all, it's fine if you want to come back to it later.

**Comment by baartosz** [comment]
Yes I am interested and looking forward to have this feature for myself.
Got a bit busy with other stuff lately after recent job change.

**Comment by redstreet** [comment]
Good to know and congrats! No worries, and no rush at all. I've been super busy with real life too, and will be a bit slow on this project temporarily.

**Comment by redstreet** [comment]
@baartosz, I'm going to close this request for now. Of interest: Martin Blais published [this new repo](https://github.com/beancount/beangrow) that does a fantastic job of computing returns, including extracting the right set of balance affecting entries and such. In the future, it would be great to incorporate beangrow into fava_investor, by giving it a helpful UI.

**Pull request closed without merging**
